blog/urls.py
from .views import (
    ArticleView, AboutView, AddArticleView, ArticleDetailView,
    ArticleLike, UpdateArticleView, DeleteArticleView)
from django.urls import path


urlpatterns = [
    path('', ArticleView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about_view'),
    path('add_article/', AddArticleView.as_view(), name='add'),
    path(
        '<slug:slug>/',
        ArticleDetailView.as_view(), name='article_detail'),
    path(
        'like/<slug:slug>',
        ArticleLike.as_view(), name='article_like'),
    path(
        'update/<slug:slug>',
        UpdateArticleView.as_view(), name='update_article'),
    path(
        'delete/<slug:slug>',
        DeleteArticleView.as_view(), name='delete_article'),
]

marblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'), name='blog_urls'),
    path('accounts/', include('allauth.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.urls import reverse

STATUS = ((0, "Draft"), (1, "Published"))


class Article(models.Model):
    title = models.CharField(max_length=255, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='articles')
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    body = models.TextField()
    featured_image = CloudinaryField('image', default='placeholder')
    slug = models.SlugField(max_length=255, unique=True)
    excerpt = models.TextField(blank=True)
    likes = models.ManyToManyField(
        User, related_name='article_likes', blank=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('home')


class Comment(models.Model):
    article = models.ForeignKey(
        Article, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['date_created']

    def __str__(self):
        return '%s - %s' % (self.article.title, self.name)

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views.generic import (
    View, ListView, DetailView, CreateView, UpdateView, DeleteView)
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .models import Article
from .forms import CommentForm


class ArticleView(ListView):
    model = Article
    template_name = 'index.html'
    queryset = Article.objects.filter(status=1).order_by('-date_created')
    paginate_by = 4


class AboutView(CreateView):
    model = Article
    template_name = 'about.html'
    fields = '__all__'


class ArticleDetailView(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Article.objects.filter(status=1)
        article = get_object_or_404(queryset, slug=slug)
        comments = article.comments.filter(
            approved=True).order_by('date_created')
        liked = False
        if article.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "article.html",
            {
                "article": article,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Article.objects.filter(status=1)
        article = get_object_or_404(queryset, slug=slug)
        comments = article.comments.filter(
            approved=True).order_by('date_created')
        liked = False
        if article.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "article.html",
            {
                "article": article,
                "comments": comments,
                "commented": True,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )


class ArticleLike(View):

    def post(self, request, slug):
        article = get_object_or_404(Article, slug=slug)

        if article.likes.filter(id=self.request.user.id).exists():
            article.likes.remove(request.user)
        else:
            article.likes.add(request.user)

        return HttpResponseRedirect(reverse('article_detail', args=[slug]))


class AddArticleView(CreateView):
    model = Article
    template_name = 'add_article.html'
    fields = (
        'title', 'slug', 'excerpt', 'body',
        'featured_image', 'status')

    def form_valid(self, form):
        f = form.save(commit=False)
        f.author = self.request.user
        f.save()
        return redirect(reverse('home'))


class UpdateArticleView(UpdateView):
    model = Article
    template_name = 'update_article.html'
    fields = (
        'title', 'slug', 'excerpt', 'body',
        'featured_image', 'status')

    def form_valid(self, form):
        f = form.save(commit=False)
        f.author = self.request.user
        f.save()
        return redirect(reverse('home'))


class DeleteArticleView(DeleteView):
    model = Article
    template_name = 'delete_article.html'
    success_url = reverse_lazy('home')

templates/about.html
{% extends "base.html" %}

{% block content %}

<!-- Page Header -->
<header class="masthead" id="about-img">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Mum Loves Representation</h1>
                    <span class="subheading">A Blog by Tomi</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- About page content -->

<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <h3>What this blog is about</h3>
                <p>I want my little girl and so many others out there to have a heirloom doll that represents her as she grows
                    and plays imaginatively. All children should play with black dolls for the purpose of encouraging diversity.
                    It is easy to get one's hands-on white dolls...that is just taken for granted. But brown dolls, black dolls,
                    and ethnic dolls are often left upon the shelf, untouched and ignored. This is tragic.</p>
          
                  <p>My mission is to get those black and brown and diverse dolls in the hands of our children and help them
                    explore their imaginations and create stories that include dolls of all colours, so that they know that
                    everyone counts, no matter the shade of their skin.
                    It is because of this, and my need for my daughter to see herself as beautiful with her melanin rich skin
                    tone, that I made the Amaris doll.</p>
          
                  <p>Amaris doll, is a gorgeous black girl with a rich dark melanin skin tone.
                    Her hair is in a set hairstyle up until the bow, but can be restyled, braided or even wrapped into 2 buns.
          
                    Amaris doll is a fabric soft doll, which means she is a doll for life. She will grow up with your little ones
                    in all stages of their lives, from play as a child to display as an adult. You could say, she is will become
                    an heirloom, that will be there through every special moment and also just for when they need a good cuddle.
                  </p>
            </div>

        </div>
    </div>

</section>
{% endblock %}

templates/add_article.html
{% extends "base.html" %}

{% block content %}

<section>
    <div class="container">
        <div class="row">

            <div class="col-lg-8 col-md-10 mt-5 mx-auto">
                {% if user.is_authenticated %}
                <h3>Add Article</h3>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-outline-dark">ADD</button>
                </form>
                {% else %}
                <h4>You need to login to use this page !!!</h4>
                {% endif %}
            </div>

        </div>
    </div>
</section>

{% endblock %}

templates/article.html
{% extends "base.html" %} {% block content %}

{% load crispy_forms_tags %}

<!-- Page Header -->
<header class="masthead" id="article-img">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1>{{ article.title }}</h1>
          <h2 class="subheading">{{ article.excerpt }}</h2>
          <span class="meta">Posted by
            <a href="{% url 'about_view' %}">{{ article.author }}</a>
            on {{ article.date_created }}
            <small>
              {% if user.is_authenticated %}
              {% if user.id == article.author.id or user.is_superuser %}
              <a href="{% url 'update_article' article.slug %}">Edit</a>
              <a href="{% url 'delete_article' article.slug %}">Delete</a>
              {% endif %}
              {% endif %}
            </small>
          </span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="text-justify">{{ article.body | safe }}</div>
        <div class="row">
          <div class="col-1">
            <strong>
              {% if user.is_authenticated %}
              <form action="{% url 'article_like' article.slug %}" class="d-inline" method="post">
                {% csrf_token %}
                {% if liked %}
                <button type="submit" value="{{ article.slug }}" class="like-btn"><i class="fas fa-heart"></i></button>
                {% else %}
                <button type="submit" value="{{ article.slug }}" class="like-btn"><i class="far fa-heart"></i></button>
                {% endif %}
              </form>
              {% else %}
              <span class="text-secondary"><i class="far fa-heart"></i></span>
              {% endif %}
              <span class="text-secondary">{{ article.number_of_likes }}</span>
            </strong>
          </div>
          <div class="col-1">
            {% with comments.count as total_comments %}
            <strong class="text-secondary"><i class="far fa-comments"></i>
              {{ total_comments }}
            </strong>
            {% endwith %}
          </div>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col">
        <hr>
      </div>
    </div>


    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <h3>Comments:</h3>
        <div class="card-body">
          {% for comment in comments %}
          <div class="comments" style="padding: 10px;">
            <p class="font-weight-bold">
              {{ comment.name }}
              <span class=" text-muted font-weight-normal">
                {{ comment.date_created }}
              </span> wrote:
            </p>
            {{ comment.body | linebreaks }}
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="card-body">
          {% if commented %}
          <div class="alert alert-success" role="alert">
            Your comment is awaiting approval
          </div>
          {% else %}

          {% if user.is_authenticated %}

          <h3>Add a comment...</h3>
          <form method="post">
            {{ comment_form | crispy }}
            {% csrf_token %}
            <button class="btn btn-outline-dark" type="submit">Post Comment</button>
          </form>
          {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</article>


{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mum Loves Representation</title>
    
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" type="text/css">

    <!-- Custom fonts for this template -->
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}" type="text/css">
    
    
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">M L R</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about_view' %}">About</a>
                    </li>
                    {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add' %}">Add Article</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
        
    {% block content %}
    {% endblock %}

    <hr>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <ul class="list-inline text-center">
            <li class="list-inline-item">
                <a href="https://code-institute-room.slack.com/team/U02A871ASHK" target="_blank" rel="noopener" 
                aria-label="Visit my Slack profile (opens in a new tab)">
                    <span class="fa-stack fa-lg">
                        <i class="fas fa-circle fa-stack-2x"></i>
                        <i class="fab fab fa-slack fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
            </li>
            <li class="list-inline-item">
                <a href="https://www.linkedin.com/in/olumbe-onabolu-07365173" target="_blank" rel="noopener" 
                aria-label="Visit my Linkedin page (opens in a new tab)">
                    <span class="fa-stack fa-lg">
                        <i class="fas fa-circle fa-stack-2x"></i>
                        <i class="fab fab fa-linkedin fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
            </li>
            <li class="list-inline-item">
                <a href="https://github.com/onabz/MAR_Blog" target="_blank" rel="noopener" 
                aria-label="Visit my MAR_Blog repository (opens in a new tab)">
                    <span class="fa-stack fa-lg">
                        <i class="fas fa-circle fa-stack-2x"></i>
                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
            </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy; Your Website <span id="copyright"></span></p>
    </footer>

    <!-- Font awesome script -->
    <script src="https://kit.fontawesome.com/369ffcbdc6.js" crossorigin="anonymous"></script>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

    <!-- Script for updating Date automatically -->
    <script>
        $("#copyright").text(new Date().getFullYear());
        // convert Post title to slug-format on front-end
    /* jshint esversion: 11 */
    let title = document.getElementById("id_title");
    let slug = document.getElementById("id_slug");
    title?.addEventListener("keyup", convertToSlug);
    slug?.addEventListener("keyup", convertToSlug);

    function convertToSlug() {
      slug.value = title.value.toLowerCase()
                 .replace(/ /g, '-')
                 .replace(/[^\w-]+/g, '');
    }

    </script>

</body>

</html>

templates/delete_article.html
{% extends "base.html" %}

{% block content %}

<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mt-5 mx-auto">
                {% if user.is_authenticated %}
                {% if user.id == article.author.id or user.is_superuser %}
                <h3>Delete: {{ article.title }}</h3>
                <br>
                <form method="post">
                    {% csrf_token %}
                    <strong>Are you sure ?</strong>
                    <br>
                    <br>
                    <button class="btn btn-outline-dark">DELETE</button>
                </form>
                {% else %}
                <h4>You are not allowed to use this page !!!</h4>
                {% endif %}
                {% else %}
                <h4>You need to login to use this page !!!</h4>
                {% endif %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<!-- Page Header -->
<header class="masthead" id="home-img">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Mum Loves Representation</h1>
                    <span class="subheading">A Blog by Tomi</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Article List -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for article in article_list %}
            <div class="post-preview">
                <a href="{% url 'article_detail' article.slug %}">
                    <h2 class="post-title">
                        {{ article.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ article.excerpt }}
                    </h3>
                </a>
                <p class="post-meta">Posted by
                    <a href="{% url 'about_view' %}">{{ article.author }}</a>
                    on {{ article.date_created }} <i class="far fa-heart"></i>
                    {{ article.number_of_likes }}   
                    <small>
                        {% if user.is_authenticated %}
                        {% if user.id == article.author.id or user.is_superuser %}
                        <a href="{% url 'update_article' article.slug %}">Edit</a>
                        <a href="{% url 'delete_article' article.slug %}">Delete</a>
                        {% endif %}
                        {% endif %}

                    </small>
                </p>
            </div>
            <hr>
            {% endfor %}
        </div>

    </div>
</div>
{% if is_paginated %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}

{% endblock %}

templates/update_article.html
{% extends "base.html" %}

{% block content %}

<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mt-5 mx-auto">
                {% if user.is_authenticated %}
                {% if user.id == article.author.id or user.is_superuser %}
                <h3>Update Article</h3>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-outline-dark">UPDATE</button>
                </form>
                {% else %}
                <h4>You are not allowed to use this page !!!</h4>
                {% endif %}
                {% else %}
                <h4>You need to login to use this page !!!</h4>
                {% endif %}
            </div>
        </div>
    </div>
</section>

{% endblock %}